In [ ]:
'''
from google.colab import drive
drive.mount('/content/gdrive')'''

Mounted at /content/gdrive


In [ ]:
'''
import os
path="/content/gdrive/My Drive"
os.chdir(path)
os.listdir(path)'''

['net_config (6).cpython-37.pyc',
 '.ipynb_checkpoints',
 'net_config (5).cpython-37.pyc',
 'EnsembleModel (1).cpython-37.pyc',
 'net_config (4).cpython-37.pyc',
 'EnsembleModel.cpython-37.pyc',
 'net_config (3).cpython-37.pyc',
 'seqGAN',
 'ML_dialogue',
 'seqGAN_tran.ipynb',
 '6000J',
 '5002',
 '5012',
 'exam5003',
 'net_config (2).cpython-37.pyc',
 'MultiLabelTextClassification',
 'net_config (1).cpython-37.pyc',
 'net_config.cpython-37.pyc',
 'MAAL.ipynb',
 '5002final',
 'MSBD5002_Fall2021_Final_Data']

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import math
import torch
import matplotlib.pyplot as plt
import math
from scipy.signal import find_peaks
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.autograd import Variable
from sklearn.preprocessing import MinMaxScaler


In [ ]:
confirmed_global = pd.read_table("MSBD5002_Fall2021_Final_Data/Q2/covid19_confirmed_global.txt",sep=',')
deaths_global = pd.read_table("MSBD5002_Fall2021_Final_Data/Q2/covid19_deaths_global.txt",sep=',')

In [ ]:
confirmed_global

Province/State      Country/Region        Lat  ...  11/27/21  11/28/21  11/29/21
0              NaN         Afghanistan  33.939110  ...    157190    157218    157260
1              NaN             Albania  41.153300  ...    199137    199555    199750
2              NaN             Algeria  28.033900  ...    209980    210152    210344
3              NaN             Andorra  42.506300  ...     16712     16712     16712
4              NaN              Angola -11.202700  ...     65139     65144     65155
..             ...                 ...        ...  ...       ...       ...       ...
275            NaN             Vietnam  14.058324  ...   1197404   1210340   1224110
276            NaN  West Bank and Gaza  31.952200  ...    459479    459479    460053
277            NaN               Yemen  15.552727  ...      9981      9987      9995
278            NaN              Zambia -13.133897  ...    210138    210143    210150
279            NaN            Zimbabwe -19.015438  ...    133836    133951    134226

[280 rows x 682 columns]

In [ ]:
confirmed_global['Province/State'] = confirmed_global['Province/State'].fillna('Country')

In [ ]:
deaths_global['Province/State'] = deaths_global['Province/State'].fillna('Country')

In [ ]:
confirmed_global['Country/Region'].value_counts()

China                 34
Canada                16
France                12
United Kingdom        12
Australia              8
                      ..
Dominican Republic     1
Kosovo                 1
Ethiopia               1
Mongolia               1
Saint Lucia            1
Name: Country/Region, Length: 196, dtype: int64

In [ ]:
confirmed_us = confirmed_global[confirmed_global['Country/Region']=='US']
deaths_us = deaths_global[deaths_global['Country/Region']=='US']

In [ ]:
deaths_us

Province/State Country/Region   Lat  ...  11/27/21  11/28/21  11/29/21
255        Country             US  40.0  ...    776536    776639    778601

[1 rows x 682 columns]

In [ ]:
confirmed_us_feat = confirmed_us[['Province/State','Country/Region','Lat','Long']]
deaths_us_feat = deaths_us[['Province/State','Country/Region','Lat','Long']]
deaths_us_time = deaths_us.drop(['Province/State','Country/Region','Lat','Long'],axis=1)
confirmed_us_time = confirmed_us.drop(['Province/State','Country/Region','Lat','Long'],axis=1)

In [ ]:
min_D = 7
max_D = 100


# the input should be a 1-D numpy array
def FindPeriod(arr):
    # initialize best period score
    best_score = float('inf')
    period = 0

    # D is the candidate period
    for d in range(min_D, max_D,7):

        # peaks locations
        p, _ = find_peaks(arr, distance=d)

        # valley locations
        v, _ = find_peaks(-arr, distance=d)

        # calculate interval lengths pd and vd from p and v
        pd = np.diff(p)
        vd = np.diff(v)

        # set current period d score
        cur_score = min(np.std(pd), np.std(vd)) / math.sqrt(d)

        if cur_score < best_score:
            best_score = cur_score
            period = d

    return period

    # convert data to 1-D numpy array
total_data=[]
total_data.append(np.diff(confirmed_us_time.to_numpy()).reshape(-1,1))

total_data.append(np.diff(deaths_us_time.to_numpy()).reshape(-1,1))


In [ ]:
period = [14]

In [3]:
input_size = 1
hidden_size = 16
num_layers = 1
num_classes = 1
batch_size = 128
#res=[]
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
criterion = nn.MSELoss().to(device)

In [2]:
def rescaler(data):
    #input_path = "/kaggle/input/mlproject/data-sets/KDD-Cup/data/001_UCR_Anomaly_35000.txt"
    #data = pd.read_csv(input_path,names=['value'])
    scaler = MinMaxScaler(feature_range=(-1, 1))
    scaler.fit(data)
    return scaler



def dataPreprocessing(time_window, data, scaler):
    data = scaler.transform(data)
    data = data.tolist()
    dataX, dataY = [], []
    for i in range(len(data)-time_window-1):
        a = data[i:(i+time_window)]
        dataX.append(a)
        dataY.append(data[i + time_window])
    #print(dataX)
    return np.array(dataX), np.array(dataY)


def data_loader(data_x, data_y, batch_size):
    dataset = TimeDataset(data_x, data_y)
    return DataLoader(dataset, batch_size=batch_size, shuffle=False, drop_last=False, num_workers=4)


class TimeDataset(Dataset):
    def __init__(self, data_x, data_y):
        self.data_x = data_x
        self.data_y = data_y

    def __getitem__(self, idx):
        data_x = self.data_x[idx]
        data_y = self.data_y[idx]

        return data_x, data_y

    def __len__(self):
        return len(self.data_x)
    
    


    
    
class LSTM(nn.Module):
    def __init__(self, num_classes, input_size, hidden_size, num_layers, device):
        super(LSTM, self).__init__()
        
        self.device = device
        self.num_classes = num_classes
        self.num_layers = num_layers
        self.input_size = input_size
        self.hidden_size = hidden_size
        #self.seq_length = seq_length
        
        self.lstm = nn.LSTM(input_size=input_size, hidden_size=hidden_size,
                            num_layers=num_layers, batch_first=True)
        
        self.fc = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        h_0 = Variable(torch.zeros(
            self.num_layers, x.size(0), self.hidden_size))
        h_0 = h_0.cuda()
        
        c_0 = Variable(torch.zeros(
            self.num_layers, x.size(0), self.hidden_size))
        c_0 = c_0.cuda()
        
        # Propagate input through LSTM
        ula, (h_out, _) = self.lstm(x, (h_0, c_0))
        
        out = h_out.view(-1, self.hidden_size)
        
        
        #print(out.shape)
        return self.fc(out)
    
    
    
    
def train(train_loader,model,optimizer):
    num_epochs = 50
    count=0 
    for epochs in range(num_epochs):
        for i,(batch_x, batch_y) in enumerate (train_loader): 
            batch_x = batch_x.float()
            #print(batch_x.shape)
            batch_x = batch_x.to(device)
            batch_y = batch_y.float()
            batch_y = batch_y.to(device)
            #print(batch_x)
            outputs = model(batch_x)
            optimizer.zero_grad()   

            loss = criterion(outputs,batch_y)
            
            if epochs==0:
                last = loss.item()
            else:
                if (last-loss.item())/last<0.01:
                    count+=1
                elif count>0:
                    count=0
                #if count>2:
                    #break
            #backpropagation 
            loss.backward()
            optimizer.step()
            #print("Epoch: %d, loss: %1.5f" % (epochs, loss.item()))
            #iter+=1
        #if count>2:
            #break
        if epochs % 5 == 0:
            print("Epoch: %d, loss: %1.5f" % (epochs, loss.item()))

            
def evaluation(test_loader):
    res=[]
    for i,(batch_x, batch_y) in enumerate (test_loader): 
        batch_x = batch_x.float()
        batch_x = batch_x.to(device)
        batch_y = batch_y.float()
        batch_y = batch_y.numpy()
        with torch.no_grad():
            outputs = model(batch_x)
        outputs = outputs.cpu()
        outputs = outputs.numpy()
        res.append(outputs)
    res = np.concatenate(res,axis=0)
    return res

In [4]:
LSTM(num_classes, input_size, hidden_size, num_layers,device)

LSTM(
  (lstm): LSTM(1, 16, batch_first=True)
  (fc): Linear(in_features=16, out_features=1, bias=True)
)

In [ ]:
hit=0
count=0
res=[[],[]]
scalers=[]
for p in period:
  for idx in range(len(total_data)):
      scaler = rescaler(total_data[idx])
      scalers.append(scaler)
      train_x,train_y=dataPreprocessing(p, total_data[idx], scaler)
      data = scaler.transform(total_data[idx])
      #print(data.shape)
      test_x = np.array([data[-p:,:]])
      print(test_x.shape)
      test_y = np.array([0])
      
      train_loader = data_loader(train_x, train_y, batch_size)
      test_loader = data_loader(test_x, test_y, batch_size)
      
      model = LSTM(num_classes, input_size, hidden_size, num_layers,device)
      model = model.to(device)
      optimizer = torch.optim.Adam(model.parameters(), lr=0.001,betas=(0.9, 0.999), eps=1e-08,
                            weight_decay=0.001, amsgrad=False)
      
      train(train_loader,model,optimizer)
      
      
      test = torch.tensor(test_x).float().reshape(1,-1,1).to(device)
      #print(test_x.shape)
      with torch.no_grad():
          outputs = model(test)
      outputs = outputs.cpu()
      outputs = outputs.numpy()
      res[idx].append(outputs)
      #print(outputs.shape)

      for i in range(6):
        test_x = test_x[:,1:,:]
        test_x = np.concatenate((test_x,outputs.reshape(1,1,1)),axis=1)
        test = torch.tensor(test_x).float().reshape(1,-1,1).to(device)
        #print(test.shape)
        with torch.no_grad():
            outputs = model(test)
        outputs = outputs.cpu()
        outputs = outputs.numpy()
        res[idx].append(outputs)
      #res.append(outputs)
      #for i in range(6):

      #test_pred = evaluation(test_loader)
      
      #res = pd.DataFrame(np.absolute(test_y-test_pred))
      #res.to_csv('MSBD5002_Fall2021_Final_Data/Q2/',index=False)
      print()

(1, 14, 1)
Epoch: 0, loss: 0.23983
Epoch: 5, loss: 0.14328
Epoch: 10, loss: 0.07918
Epoch: 15, loss: 0.08164
Epoch: 20, loss: 0.07985
Epoch: 25, loss: 0.08017
Epoch: 30, loss: 0.07972
Epoch: 35, loss: 0.08472
Epoch: 40, loss: 0.08786
Epoch: 45, loss: 0.08752

(1, 14, 1)
Epoch: 0, loss: 0.21709
Epoch: 5, loss: 0.13634
Epoch: 10, loss: 0.09526
Epoch: 15, loss: 0.09562
Epoch: 20, loss: 0.09806
Epoch: 25, loss: 0.09934
Epoch: 30, loss: 0.09659
Epoch: 35, loss: 0.09548
Epoch: 40, loss: 0.09501
Epoch: 45, loss: 0.09484



In [ ]:
for i in range(len(res)):
  print([int(scalers[i].inverse_transform(j).tolist()[0][0]) for j in res[i]])

[91609, 91240, 90498, 89846, 88685, 92045, 94998]
[844, 817, 782, 759, 728, 730, 736]


In [ ]:
res[0]

[array([[0.8947974]], dtype=float32),
 array([[0.89323467]], dtype=float32),
 array([[0.8923458]], dtype=float32),
 array([[0.8916535]], dtype=float32),
 array([[0.8910987]], dtype=float32),
 array([[0.8906553]], dtype=float32),
 array([[0.8902894]], dtype=float32)]

**Task 2**

In [ ]:
confirmed_global.values

array([['Country', 'Afghanistan', 33.93911, ..., 157190, 157218, 157260],
       ['Country', 'Albania', 41.1533, ..., 199137, 199555, 199750],
       ['Country', 'Algeria', 28.0339, ..., 209980, 210152, 210344],
       ...,
       ['Country', 'Yemen', 15.552726999999999, ..., 9981, 9987, 9995],
       ['Country', 'Zambia', -13.133897, ..., 210138, 210143, 210150],
       ['Country', 'Zimbabwe', -19.015438, ..., 133836, 133951, 134226]],
      dtype=object)

In [ ]:
confirm_oct={}
oct = confirmed_global['10/1/21'] - confirmed_global['9/30/21']
confirmed_global = confirmed_global.values
for i in range(confirmed_global.shape[0]):
  if math.isnan(confirmed_global[i][2]) or math.isnan(confirmed_global[i][3]) or math.isnan(oct[i]):
    continue
  confirm_oct[(confirmed_global[i][2], confirmed_global[i][3])] = oct[i]
s = sum(oct)

In [ ]:
import folium
map = folium.Map(location=[32, 120], zoom_start=5)
for loc, c in confirm_oct.items():
    lat, lng = loc
    
    folium.CircleMarker(
            [lat, lng],
            radius=int(c/s),
      color='orange',
      fill_color='orange'
      ).add_to(map)

In [ ]:
map.save('5002final/wjy/map.html')